"""
DanceCoach AI Backend — FastAPI server with PoseScript-inspired feedback.

Endpoints:
- POST /api/feedback — Generate AI coaching feedback using Nemotron + PoseScript descriptions
- POST /api/describe — Describe a pose in natural language (PoseScript-style)
- POST /api/correct — Generate PoseFix-style corrections between two poses
- GET  /api/health — Health check
"""

import os
import httpx
from dotenv import load_dotenv
from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
from typing import Optional
from pose_descriptor import describe_pose, describe_correction, describe_session_corrections

load_dotenv(dotenv_path=os.path.join(os.path.dirname(__file__), '..', '.env'))

app = FastAPI(title="DanceCoach AI Backend", version="1.0.0")

DEFAULT_ALLOWED_ORIGINS = [
    "https://fcistud.github.io",
    "http://localhost:5174",
    "http://localhost:5173",
    "http://localhost:3000",
]


def parse_allowed_origins(origins_text: str) -> list[str]:
    if not origins_text:
        return DEFAULT_ALLOWED_ORIGINS.copy()

    origins = [origin.strip() for origin in origins_text.split(",") if origin.strip()]
    if not origins:
        return DEFAULT_ALLOWED_ORIGINS.copy()

    if "https://fcistud.github.io" not in origins:
        origins.append("https://fcistud.github.io")
    return origins


ALLOWED_ORIGINS = parse_allowed_origins(os.getenv("ALLOWED_ORIGINS", ""))

# CORS — allow frontend origins via env (Render) with local defaults
app.add_middleware(
    CORSMiddleware,
    allow_origins=ALLOWED_ORIGINS,
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# ─── Config ───
NEMOTRON_API_URL = "https://integrate.api.nvidia.com/v1/chat/completions"
NEMOTRON_MODEL = "nvidia/llama-3.3-nemotron-super-49b-v1"
NVIDIA_API_KEY = os.getenv("VITE_NEMOTRON_API_KEY", "")

SYSTEM_PROMPT = """You are DanceCoach AI, an expert dance instructor powered by PoseScript body awareness.

You receive PRECISE, ANATOMICAL descriptions of body poses generated by a PoseScript-inspired analysis system. These descriptions tell you exactly what the dancer's body is doing vs what it should be doing.

Your job is to TRANSLATE these technical pose descriptions into warm, practical dance coaching.

RULES:
- Keep under 250 words
- Be warm, encouraging, and specific
- Translate anatomical descriptions into dancer-friendly language
- Focus on the 2-3 most impactful corrections
- Use analogies dancers understand ("imagine reaching for the ceiling", "pretend you're holding a beach ball")
- Reference specific timestamps when provided (format: XXs)
- End with one specific exercise to practice the weakest area first
- DON'T repeat the technical descriptions verbatim — rephrase them for a dancer"""


# ─── Models ───
class FeedbackRequest(BaseModel):
    session_analysis: dict  # From frontend feedbackEngine.analyzeSession()
    session_frames: Optional[list] = None  # Optional: raw frames with landmarks for PoseScript
    api_key: Optional[str] = None


class PoseDescribeRequest(BaseModel):
    landmarks: list  # MediaPipe 33-point landmarks


class CorrectionRequest(BaseModel):
    ref_landmarks: list
    user_landmarks: list


# ─── Endpoints ───

@app.get("/health")
@app.get("/api/health")
async def health():
    return {"status": "ok", "posescript": True, "nemotron": bool(NVIDIA_API_KEY)}


@app.post("/describe")
@app.post("/api/describe")
async def describe(req: PoseDescribeRequest):
    """Describe a pose in natural language using PoseScript vocabulary."""
    description = describe_pose(req.landmarks)
    return {"description": description}


@app.post("/correct")
@app.post("/api/correct")
async def correct(req: CorrectionRequest):
    """Generate PoseFix-style correction text between two poses."""
    correction = describe_correction(req.ref_landmarks, req.user_landmarks)
    return {"correction": correction}


@app.post("/feedback")
@app.post("/api/feedback")
async def feedback(req: FeedbackRequest):
    """
    Generate AI coaching feedback combining:
    1. PoseScript-style pose descriptions (local analysis)
    2. Nemotron AI for natural language coaching (API)
    """
    api_key = req.api_key or NVIDIA_API_KEY
    if not api_key:
        raise HTTPException(status_code=400, detail="No API key provided. Set VITE_NEMOTRON_API_KEY in .env or pass api_key.")

    analysis = req.session_analysis
    session_frames = req.session_frames or []

    # ─── Step 1: Generate PoseScript descriptions for worst moments ───
    posescript_context = ""
    if session_frames:
        result = describe_session_corrections(session_frames)
        posescript_context = "\n\nPOSESCRIPT BODY ANALYSIS (precise anatomical descriptions):\n"
        posescript_context += f"Average accuracy: {result['avg_score']:.0f}%\n"
        posescript_context += f"Total frames analyzed: {result['total_frames']}\n\n"

        if result.get('reference_description'):
            posescript_context += f"Reference pose description:\n{result['reference_description']}\n\n"

        for i, corr in enumerate(result.get('corrections', [])[:3]):
            posescript_context += f"Problem moment #{i+1} (at {corr['timestamp']:.0f}s, score: {corr['score']:.0f}%):\n"
            posescript_context += f"{corr['correction']}\n\n"

    # ─── Step 2: Build prompt from session analysis + PoseScript ───
    prompt = build_prompt(analysis, posescript_context)

    # ─── Step 3: Call Nemotron ───
    try:
        async with httpx.AsyncClient(timeout=30.0) as client:
            resp = await client.post(
                NEMOTRON_API_URL,
                headers={
                    "Content-Type": "application/json",
                    "Authorization": f"Bearer {api_key}",
                },
                json={
                    "model": NEMOTRON_MODEL,
                    "messages": [
                        {"role": "system", "content": SYSTEM_PROMPT},
                        {"role": "user", "content": prompt},
                    ],
                    "max_tokens": 400,
                    "temperature": 0.7,
                    "top_p": 0.9,
                    "stream": False,
                },
            )

        if resp.status_code != 200:
            raise HTTPException(
                status_code=resp.status_code,
                detail=f"Nemotron API error: {resp.text}"
            )

        data = resp.json()
        ai_text = data.get("choices", [{}])[0].get("message", {}).get("content", "")

        return {
            "feedback": ai_text,
            "posescript_analysis": posescript_context if posescript_context else None,
            "model": NEMOTRON_MODEL,
        }

    except httpx.TimeoutException:
        raise HTTPException(status_code=504, detail="Nemotron API timed out. Try again.")
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


def build_prompt(analysis: dict, posescript_context: str) -> str:
    """Build the user prompt from session analysis + PoseScript descriptions."""
    p = "Analyze my dance session and give coaching feedback:\n\n"

    overall_avg = analysis.get('overallAvg', 0)
    p += f"Overall accuracy: {overall_avg:.0f}%\n\n"

    focus_areas = analysis.get('focusAreas', [])
    if focus_areas:
        p += "PROBLEM AREAS:\n"
        for area in focus_areas[:3]:
            p += f"- {area.get('label', '?')}: {area.get('avg', 0):.0f}% match"
            trend = area.get('trend', 0)
            if trend > 5:
                p += f" [improving +{trend:.0f}%]"
            elif trend < -5:
                p += f" [declining {trend:.0f}%]"
            p += "\n"
        p += "\n"

    strengths = analysis.get('strengths', [])
    if strengths:
        p += "STRONG AREAS: " + ", ".join(
            f"{s.get('label', '?')} ({s.get('avg', 0):.0f}%)" for s in strengths
        ) + "\n\n"

    timeline = analysis.get('timeline', [])
    if timeline:
        p += "TIMELINE:\n"
        for phase in timeline:
            p += f"- {phase.get('label', '?')}: {phase.get('avg', 0)}%"
            ws = phase.get('weakestSegment')
            if ws:
                p += f" (weakest: {ws} at {phase.get('weakestScore', '?')}%)"
            p += "\n"
        p += "\n"

    # Add PoseScript analysis
    if posescript_context:
        p += posescript_context

    p += "\nUsing the PoseScript anatomical descriptions above, give me specific, actionable corrections. Describe what my body SHOULD be doing vs what it IS doing. What should I practice first?"

    return p


if __name__ == "__main__":
    import uvicorn
    print("🚀 Starting DanceCoach AI Backend on port 8000...")
    print(f"   NVIDIA API Key: {'✅ configured' if NVIDIA_API_KEY else '❌ not set'}")
    print(f"   Model: {NEMOTRON_MODEL}")
    print(f"   PoseScript: ✅ enabled")
    print(f"   Allowed Origins: {', '.join(ALLOWED_ORIGINS)}")
    uvicorn.run(app, host="0.0.0.0", port=8000, log_level="info")
